name: first workflow by. Mohamed Taha

on:
  push: 
    branches: 
      - master

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print a welcome messsage
        run: echo "welcome dear"

      - name: checkout actions 
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build spring abd creating jar file
        run: run: mvn clean install -DskipTests

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
           username: ${{ secrets.DOCKER_USER_NAME }}
           password: ${{ secrets.DOECKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER_NAME }}/springboot-app:latest
          docker build -t $IMAGE_NAME .

      - name: docker push
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER_NAME }}/springboot-app:latest
          docker push $IMAGE_NAME
          

      
          
        

      - name: list repos files
        run: ls -h
