name: first workflow by. Mohamed Taha

on:
  push: 
    branches: 
      - master

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print a welcome messsage
        run: echo "welcome dear"

      - name: checkout actions 
        uses: actions/checkout@v4.2.2

      - name: list repos files
        run: ll -h 
